# Copyright (C) 2025 Nobleo Autonomous Solutions B.V.

# Let's make sure we fullfill the pre-commit requirements ourselves in this repository
repos:
  - repo: https://bitbucket.org/nobleo/nobleo-pre-commit
    rev: 24.9.0
    hooks:
    - id: nobleo-hooks
      verbose: true
  - repo: local
    hooks:
    - id: copyright
      name: Add missing copyright
      language: python
      additional_dependencies: [reuse]
      entry: reuse annotate --copyright 'Nobleo Autonomous Solutions B.V.' --copyright-style string-c --skip-existing --skip-unrecognised
      types: [text]
