# Copyright (C) 2025 Nobleo Autonomous Solutions B.V.

# Hook containing all other hooks:
- id: nobleo-hooks
  name: nobleo-hooks
  language: script
  entry: ./run-nobleo-hooks
  require_serial: true

# Custom hooks:
- id: bumpver
  name: bumpver
  description: All versions in the project should be aligned
  language: python
  additional_dependencies: [bumpver]
  types: [text]
  pass_filenames: false
  entry: verify-bumpver

- id: launch-depends
  name: launch-depends
  description: Verify that all launch dependencies are listed in package.xml
  language: python
  types: [xml]
  files: \.launch\.xml$
  pass_filenames: true
  entry: verify-launch-depends

- id: xml-schema
  name: xml-schema
  description: Validate XML files against their declared XSD schema
  language: python
  additional_dependencies: [xmlschema]
  types: [xml]
  pass_filenames: true
  entry: verify-xml-schema
