definitions:
  caches:
    pre-commit: ~/.cache/pre-commit
  steps:
    - step: &nobleo-pre-commit
        name: Pre-commit
        image: nobleo/pre-commit:4
        caches: [pre-commit]
        script:
          - git config --global --add safe.directory /app
          - pre-commit run --all-files --verbose

pipelines:
  default:
    - step: *nobleo-pre-commit

  custom:
    deploy-docker:
      - step:
          name: Deploy Docker
          services:
            - docker
          script:
            - echo "${DOCKER_HUB_PUSH_PASSWORD}" | docker login --username "${DOCKER_HUB_PUSH_USERNAME}" --password-stdin
            - docker build . -t "nobleo/pre-commit:4"  # Same version as pre-commit
            - docker push "nobleo/pre-commit:4"
