# Copyright (C) 2025 Nobleo Autonomous Solutions B.V.

[bumpver]
current_version = "26.7.1"
version_pattern = "YY.MM.INC0"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"README.md" = ["{version}"]
"bumpver.toml" = ['current_version = "{version}"']
"pyproject.toml" = ['version = "{version}"']
