#!/usr/bin/env python3
import argparse
import os
import shutil

HERE = os.path.dirname(os.path.realpath(__file__))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--skip', action='append', default=[])
    parser.add_argument('files', nargs='*')
    args = parser.parse_args()

    if args.skip:
        existing = os.environ.get('SKIP', '')
        skips = [s for s in existing.split(',') if s] + args.skip
        os.environ['SKIP'] = ','.join(skips)

    # Use prek if available
    cfg = os.path.join(HERE, 'nobleo-hooks.yaml')
    args = ['--config', cfg, '--files'] + args.files
    if shutil.which('prek'):
        cmd = ['prek', 'run', '--no-progress', '--hide-status', 'skipped'] + args
    else:
        cmd = ['pre-commit', 'run'] + args
    os.execvp(cmd[0], cmd)


if __name__ == '__main__':
    exit(main())
